name: Testing
on: push
jobs:
  Run-All-Jest-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка проекта
        uses: actions/checkout@v4
      - name: Установка зависимостей
        run: npm ci
      - name: Запуск тестов
        run: npm run test
